import { AcademicData } from '../types';

export const INITIAL_SAMPLE_DATA: AcademicData = {
  profileName: 'Abrar Rahman',
  studentId: '221-15-4321',
  department: 'Computer Science & Engineering',
  semesters: [
    {
      id: 'sem-1',
      semesterName: 'Spring 2023 (Semester 1)',
      gpa: 3.42,
      credits: 15,
      courses: [
        { id: 'c-101', courseName: 'Structured Programming', courseCode: 'CSE111', credits: 3, letterGrade: 'A', gradePoint: 3.75 },
        { id: 'c-102', courseName: 'Structured Programming Lab', courseCode: 'CSE112', credits: 1, letterGrade: 'A+', gradePoint: 4.00 },
        { id: 'c-103', courseName: 'Discrete Mathematics', courseCode: 'CSE122', credits: 3, letterGrade: 'B+', gradePoint: 3.25 },
        { id: 'c-104', courseName: 'Calculus & Analytical Geometry', courseCode: 'MAT101', credits: 3, letterGrade: 'B', gradePoint: 3.00 },
        { id: 'c-105', courseName: 'English Reading & Writing', courseCode: 'ENG101', credits: 3, letterGrade: 'A-', gradePoint: 3.50 },
        { id: 'c-106', courseName: 'Physics I', courseCode: 'PHY101', credits: 2, letterGrade: 'B+', gradePoint: 3.25 },
      ],
    },
    {
      id: 'sem-2',
      semesterName: 'Summer 2023 (Semester 2)',
      gpa: 3.55,
      credits: 16,
      courses: [
        { id: 'c-201', courseName: 'Object Oriented Programming', courseCode: 'CSE123', credits: 3, letterGrade: 'A', gradePoint: 3.75 },
        { id: 'c-202', courseName: 'OOP Lab', courseCode: 'CSE124', credits: 1, letterGrade: 'A+', gradePoint: 4.00 },
        { id: 'c-203', courseName: 'Data Structures', courseCode: 'CSE211', credits: 3, letterGrade: 'A-', gradePoint: 3.50 },
        { id: 'c-204', courseName: 'Data Structures Lab', courseCode: 'CSE212', credits: 1, letterGrade: 'A+', gradePoint: 4.00 },
        { id: 'c-205', courseName: 'Linear Algebra', courseCode: 'MAT102', credits: 3, letterGrade: 'B+', gradePoint: 3.25 },
        { id: 'c-206', courseName: 'Digital Logic Design', courseCode: 'EEE101', credits: 3, letterGrade: 'A-', gradePoint: 3.50 },
        { id: 'c-207', courseName: 'Digital Logic Design Lab', courseCode: 'EEE102', credits: 2, letterGrade: 'A', gradePoint: 3.75 },
      ],
    },
    {
      id: 'sem-3',
      semesterName: 'Fall 2023 (Semester 3)',
      gpa: 3.71,
      credits: 15,
      courses: [
        { id: 'c-301', courseName: 'Algorithms', courseCode: 'CSE221', credits: 3, letterGrade: 'A+', gradePoint: 4.00 },
        { id: 'c-302', courseName: 'Algorithms Lab', courseCode: 'CSE222', credits: 1, letterGrade: 'A+', gradePoint: 4.00 },
        { id: 'c-303', courseName: 'Database Management Systems', courseCode: 'CSE231', credits: 3, letterGrade: 'A', gradePoint: 3.75 },
        { id: 'c-304', courseName: 'DBMS Lab', courseCode: 'CSE232', credits: 1, letterGrade: 'A', gradePoint: 3.75 },
        { id: 'c-305', courseName: 'Statistics & Probability', courseCode: 'STA101', credits: 3, letterGrade: 'B+', gradePoint: 3.25 },
        { id: 'c-306', courseName: 'Computer Architecture', courseCode: 'CSE223', credits: 4, letterGrade: 'A-', gradePoint: 3.50 },
      ],
    },
    {
      id: 'sem-4',
      semesterName: 'Spring 2024 (Semester 4)',
      gpa: 3.80,
      credits: 16,
      courses: [
        { id: 'c-401', courseName: 'Operating Systems', courseCode: 'CSE311', credits: 3, letterGrade: 'A+', gradePoint: 4.00 },
        { id: 'c-402', courseName: 'Operating Systems Lab', courseCode: 'CSE312', credits: 1, letterGrade: 'A+', gradePoint: 4.00 },
        { id: 'c-403', courseName: 'Software Engineering', courseCode: 'CSE321', credits: 3, letterGrade: 'A', gradePoint: 3.75 },
        { id: 'c-404', courseName: 'Computer Networks', courseCode: 'CSE331', credits: 3, letterGrade: 'A-', gradePoint: 3.50 },
        { id: 'c-405', courseName: 'Networks Lab', courseCode: 'CSE332', credits: 1, letterGrade: 'A+', gradePoint: 4.00 },
        { id: 'c-406', courseName: 'Numerical Methods', courseCode: 'MAT201', credits: 3, letterGrade: 'A', gradePoint: 3.75 },
        { id: 'c-407', courseName: 'Economics & Accounting', courseCode: 'BUS101', credits: 2, letterGrade: 'A', gradePoint: 3.75 },
      ],
    },
  ],
  savedCourseCalculations: [
    {
      courseName: 'Web Engineering',
      courseCode: 'CSE333',
      creditHours: 3,
      attendanceMark: 7,
      quiz1Mark: 14,
      quiz2Mark: 12,
      quiz3Mark: 15,
      quizAverage: 13.67,
      assignmentMark: 5,
      presentationMark: 8,
      midTermMark: 23,
      finalExamMark: 36,
      totalMark: 92.67,
      letterGrade: 'A+',
      gradePoint: 4.00,
    },
  ],
};
